//======================================================================
// File: APB_SEQUENCER.sv
// Description: Sequencer for APB transactions
// Author: Y.V.PAVAN KUMAR
// Notes: Acts as the arbiter between sequences and driver.
//        Provides transactions generated by sequences to the driver.
//======================================================================

class apb_sequencer extends uvm_sequencer#(apb_transaction);
  `uvm_component_utils(apb_sequencer) 
  // Registers this sequencer with UVM factory, enabling create() and overrides

  // Constructor: initializes sequencer with a name and parent component
  function new(string name="apb_sequencer", uvm_component parent);
    super.new(name, parent);
  endfunction

endclass
